// <auto-generated />
namespace WiodySM.Data.Configuration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V22));
        
        string IMigrationMetadata.Id
        {
            get { return "201901170631465_V22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
